source 'https://rubygems.org'

gem 'awesome_print'
gem 'gli'
gem 'listen', require: false
gem 'redis'
gem 'redis-namespace'

gem 'pry', require: false
gem 'rspec', require: false
gem 'rubocop', require: false
gem 'rubocop-rspec', require: false
gem 'simplecov', require: false
gem 'super_diff', require: false
