#!/bin/sh

CACHE_TIME=60

case $OSTYPE in
    darwin*)
        # Sample `pmset -g batt` output (second line)
        # -InternalBattery-0     100%; charged; 0:00 remaining
        # -InternalBattery-0     100%; discharging; (no estimate)
        # -InternalBattery-0     83%; discharging; 4:57 remaining
        # -InternalBattery-0     21%; charging; 2:36 remaining
        cache=$TMPDIR/skanev.tmux.battery

        if [ ! -f $cache ] || ((`date +%s` - `/usr/bin/stat -f "%m" $cache` > $CACHE_TIME)) ; then
            pmset -g batt |
                awk '/InternalBattery-.*discharg/ { gsub(";", "", $3); printf " 🔋 %s ", $3; } \
                     /discharging; [1-9]+:[0-9]+/ { printf "%sh ", $5 } \
                     /discharging; 0:[0-9]+/ { gsub("0:", "", $5); printf "%sm ", $5 }' > \
                $cache
        fi

        cat $cache
        ;;
    *)
        ;;
esac
