#!/usr/bin/env zsh

current_program=$(~/.scripts/tmux/current-app)

if [[ "$current_program" == "vim" ]]; then
  tmux send-keys M-c
elif [[ $DOTFILES_OS == mac ]]; then
  tmux show-buffer | pbcopy
  tmux display "Copied to clipboard"
else
  tmux show-buffer | xclip -selection clipboard
  tmux display "Copied to clipboard"
fi
