#!/bin/sh

prefix=$(tmux show-option -vg @meta-prefix)
current_program=$(~/.scripts/tmux/current-app)

if [ "$current_program" == "vim" ]; then
    tmux send-keys "$prefix" \; send-keys c
else
    tmux show-buffer | xclip -selection clipboard
    tmux display "Copied to clipboard"
fi
