#!/usr/bin/env zsh

current_program=$(~/.scripts/tmux/current-app)

if [[ "$current_program" == "vim" ]]; then
  tmux send-keys M-c
elif [[ -n $DOTFILES_WSL ]]; then
  tmux show-buffer | clip.exe
  tmux display "Copied to clipboard"
else
  tmux show-buffer | pbcopy
  tmux display "Copied to clipboard"
fi
