#!/bin/dash

set -e

case $1/$2 in
    ruby/vim)
        printf "vim"
        ;;

    mutt/vim)
        printf "vim"
        ;;

    cheat/vim)
        printf "vim"
        ;;

    less/vim)
        printf "vim"
        ;;

    Vim/*)
        printf "vim"
        ;;

    *)
        printf "%s" $1
        ;;
esac
