#!/usr/bin/env zsh

local name=$(tmux display -p '#{pane_current_command}/#{window_name}')

case $name in
    ruby/vim)
        printf "vim"
        ;;

    mutt/vim)
        printf "vim"
        ;;

    cheat/vim)
        printf "vim"
        ;;

    less/vim)
        printf "vim"
        ;;

    Vim/*)
        printf "vim"
        ;;

    *)
        printf "%s" ${name/\/*/}
        ;;
esac
