#!/bin/sh

status=$(tmux display -p '#{pane_current_command}/#{window_name}')

case $status in
    ruby/vim)
        printf "vim"
        ;;

    mutt/vim)
        printf "vim"
        ;;

    cheat/vim)
        printf "vim"
        ;;

    Vim/*)
        printf "vim"
        ;;

    *)
        printf "%s" ${status/\/*/}
        ;;
esac
