#!/bin/bash

if [ $(tmux display -p '#W') == 'mutt' ]; then
    if pgrep -f mutt/bin/fetch-email &>/dev/null; then
        echo "(sync)"
        exit 0
    fi

    now=$(date "+%s")
    checked=$(cat ~/.mutt/temp/last-fetched)
    age=$((now - checked))


    if [ $age -lt 60 ]; then
        echo "$age sec"
    elif [ $age -lt $((60 * 60)) ]; then
        minutes=$((age / 60))
        echo "$minutes min"
    elif [ $age -lt $((60 * 60 * 24)) ]; then
        hours=$((age / (60 * 60)))
        echo "$hours hr"
    else
        days=$((age / (60 * 60 * 24)))
        echo "$days day(s)"
    fi
else
    hostname -s
fi

