#!/usr/bin/env zsh

local urls=($(tmux capture-pane -p | grep -iIohE 'https?://[^[:space:]]+' | sort -u))

case ${#urls} in
  (0)
    tmux display "No URLs found"
    ;;

  (1)
    ~/.scripts/open-browser ${urls[1]}
    ;;

  (*)
    local selected=($(echo ${(F)urls} | fzf-tmux -m -p 70%,50%))
    local url
    for url in $selected; do
      echo ~/.scripts/open-browser $url
    done
    ;;
esac
