#!/bin/zsh

prefix=$(tmux show-option -vg @meta-prefix)
current_program=$(~/.scripts/tmux/current-app)

if [[ $current_program == "vim" ]]; then
    tmux send-keys "$prefix" \; send-keys v
else
    tmux load-buffer =(pbpaste) \; paste-buffer
fi
