#!/bin/sh

PREFIX="[24;6~"

switch_to_tab() {
    tmux select-window -t $1 \; refresh-client -S
}

app=$(tmux display -p '#W')
tab_escape=$(tmux show -v @tab-escape)

while [[ $1 == -* ]]; do
    case "$1" in
        -t) app="yes"
            shift
            ;;
        -e) tmux set -q @tab-escape yes
            exit
            ;;
        -*) break
            ;;
    esac
done

tab=$1

if [ "$tab_escape" == "yes" ]; then
    tmux set -q @tab-escape no
    switch_to_tab $tab
    exit
fi

case "$app" in
    vim)
        tmux send-keys "$PREFIX$tab"
        ;;
    *)
        switch_to_tab $tab
        ;;
esac
