#!/bin/dash

set -e

switch_to_tab() {
    tmux set '@tab-escape' no \; select-window -t $1 \; refresh-client -S
}

case $1 in
  (--determine)
    if [ "$4" = yes ]; then
      switch_to_tab $5
    else
      app=$(~/.scripts/tmux/current-app $2 $3)

      case "$app" in
        (vim|Vim|nvim)
          tmux send-keys "M-$5"
          ;;

        (*)
          switch_to_tab $5
      esac

    fi
    ;;

  (--of-tmux)
    switch_to_tab $2
    ;;

  (--escape-next)
    tmux set '@tab-escape' yes
    ;;

  (*)
    echo "Don't know how to handle options: $*"
    tmux display "Don't know how to handle options: $*"
    ;;
esac
