#!/usr/bin/env zsh

source setup/shared

install-pack() {
  [[ ! -d ~/.pyenv ]] && run-with-status "cloning pyenv" "git clone https://github.com/pyenv/pyenv.git ~/.pyenv"

  [[ ! -d ~/.pyenv/plugins/pyenv-virtualenv ]] && run-with-status \
      "cloning pyenv-virtualenv" \
      "git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv"
}

is-pack-installed() {
  [[ -d ~/.pyenv && -x ~/.pyenv/bin/pyenv && -d ~/.pyenv/plugins/pyenv-virtualenv ]]
}

verify-pack() {
  # TODO real-er check
  zsh -l -c 'which pyenv > /dev/null' || croak 'pyenv does not seem to be installed'
}

pack-info() {
}

process-pack $1
