#!/usr/bin/env zsh

source setup/shared

install-pack() {
  mkdir -p ~/.config/ranger/plugins

  if [[ ! -d ~/.config/ranger/plugins/ranger_devicons/.git ]] ; then
    git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
  fi

  (cd ~/.config/ranger/plugins/ranger_devicons && git pull)
}

is-pack-installed() {
  # TODO
  false
}

verify-pack() {
  # TODO
}

pack-info() {
  # TODO
}

process-pack $1
