#!/usr/bin/env zsh

case $OSTYPE in
    darwin*)
        sudo command htop "$@"
        ;;
    linux-gnu)
        command htop "$@"
        ;;
    *)
        print "Don't know how to run it on $OSTYPE"
        exit 1
        ;;
esac
