#!/usr/bin/env zsh

local name

local -a local_files=(
  ~/.localrc
  ~/.localprofile
  ~/.localenv
  ~/.gitconfig.local
  ~/.vim/tweaks.local.vim
  ~/.vim/localvimrc.vim
)

for name in $local_files; do
  if [[ -f $name ]]; then
    echo "\e[1m========================================="
    echo "file: $name"
    echo "=========================================\e[0m"
    bat --decorations never $name
    echo
  fi
done

