#!/usr/bin/env zsh

case $OSTYPE in
    darwin*)
        open /Applications/Google\ Chrome.app --args --disable-web-security
        ;;
    linux-gnu)
        chromium-browser --disable-web-security
        ;;
    *)
        print "Don't know how to run it on $OSTYPE"
        exit 1
        ;;
esac
