#!/usr/bin/env zsh

emulate -LR zsh
setopt errreturn
local first_commit
local last_merge

case $1 in
    first-commit)
        echo -n $(wip list | tail -1 | cut -d ' ' -f 1)
        ;;

    list)
        first_commit=$(git rev-list --max-parents=0 HEAD)
        last_merge=$(git rev-list --merges -1 HEAD)
        git rev-list --oneline ${last_merge:-$first_commit}..HEAD |
            while read -r line; do
                if [[ $line =~ '^[0-9a-f]+ WIP' ]]; then
                    echo $line;
                else
                    break;
                fi;
            done
        ;;

    diff)
        git diff $(wip first-commit)~1
        ;;

    compact)
        first_commit=$(wip first-commit)

        if [ -z "$first_commit" ]; then
            echo "error: No WIP commits" 1>&2
            return 1
        fi

        git reset --soft $first_commit~1
        git commit -n -m WIP
        ;;

    commit)
        wip compact
        git commit --amend --verbose
        ;;

    check)
        shift
        git add .
        git commit -n -m "WIP $*"
        ;;

    '')
        wip check
        ;;

    *)
        echo "Unknown command $1"
        ;;
esac
