#!/usr/bin/env zsh
# When invoked from a graphical program, it positions the window where I want
# it to be. For the time being, it's a lot of hackiness specifically for my
# WSL2 setup, but one day... ah, one can hope.

position-with-xdotool() {
  pid=$1
  x=$2
  y=$3
  w=$4
  h=$5

  wid=$(xdotool search --onlyvisible --pid $pid)
  xdotool windowmove $wid $x $y
  xdotool windowsize $wid $w $h
}

case $1 in
  (neovide)
    (
      cd ~/code/personal/dotfiles
      AutoHotKey.exe ahk/PositionWindow.ahk "ahk_exe neovide.exe" -9 2 1938 2097
    )
    ;;

  (gvim)
    position-with-xdotool $2 3 47 1910 2053
    ;;

  (kitty)
    position-with-xdotool $DOTFILES_KITTY_PID 1926 47 1910 2053
    ;;

  (*)
    echo "Don't know how to position you. Args: $*"
    exit 1
    ;;
esac
