#!/bin/bash

if [ $(tmux display -p '#W') == 'mutt' ]; then
    if pgrep -f mutt/bin/fetch-email &>/dev/null; then
        echo "(sync)"
        exit 0
    fi

    now=$(date "+%s")
    checked=$(cat ~/.mutt/temp/last-fetched)
    age=$((now - checked))

    if [ $age -lt 60 ]; then
        echo "$age sec"
    else
        minutes=$((age / 60))
        echo "$minutes min"
    fi
else
    hostname -s
fi

