#!/usr/bin/env zsh
alias reload_aliases="source ~/.zsh/aliases"
alias aliases="vim ~/.zsh/aliases && reload_aliases"
alias localrc="vim ~/.localrc && source ~/.localrc"

alias tmux="tmux -2"

alias ll="ls -laG"
alias rdm="rake db:migrate"
alias rdtp="rake db:test:prepare"
alias rdmr="rake db:migrate:redo"
alias rrs="bundle exec rake spec"
alias rco="rake cypress:open"
alias rcr="rake cypress:run"

alias rg="rails generate"
alias rmig="rails generate migration"

alias g="git"
alias gp="git push"
alias gg="git status"
alias grm="git rebase origin/master"
alias grim="git rebase -i origin/master"
alias gs="git stash"
alias gsa="git stash apply"
alias gsc="git stash clear"
alias gsp="git stash pop"
alias grc="git rebase --continue"
alias gca="git commit --amend"
alias gr10="git rebase -i HEAD~10"
alias gdc="echo \"You mean 'gds', right?\""
alias gds="git diff --cached"
alias gdsp="git diff --cached P"
alias gri='git rebase -i $(git rev-list --all --merges | head -1)'
alias gd="git diff"
alias gdp="git diff P"
alias gl="git last"
alias glp="git last P"

alias t="tmux"
alias ta="tmux-attach-current"
alias tat="tmux attach"

alias m="make"
alias be="bundle exec"
alias vii="gvim --remote-silent"
alias gemopen="BUNDLER_EDITOR='zsh -ci vig' bundle open"

alias clj="rlwrap --quote-characters=\"'\" --command clojure clj"
alias gist="gist -o"

alias pd="(ruby ~/code/personal/cleric/wut.rb | less -FXRS)"
alias ped="perl -pe"

alias wdp="wip diff P"

alias ch="cheat"

alias weather="curl -s wttr.in"
alias weather2="curl -s v2.wttr.in"

alias markoff="open -a Markoff"

alias zk="explain-bindkey"
alias keys="~/.scripts/keymaps =(bindkey -L)"
alias args="printf '⟪%s⟫\n'"

alias gitconfig="vim ~/.gitconfig"

alias -g RERR="2>&1"
alias -g P="| pd"

alias stalker=~/.scripts/stalker
