#!/bin/zsh

### Options ################################################
# I got this stuff from random browsing through man zshoptions

setopt AUTO_CD       # '$ foo' means '$ cd foo' if 'foo' is not a command
setopt AUTO_PUSHD    # 'cd' is now cooler
setopt PUSHD_IGNORE_DUPS
DIRSTACKSIZE=15

### Prompt #################################################
autoload -U colors
colors
setopt prompt_subst
setopt transient_rprompt

prompt_zsh_level() {
  if [[ -n $TMUX && $SHLVL > 2 ]]; then
    printf '∎'%.0s {3..$SHLVL}
  elif [[ -z $TMUX && $SHLVL > 1 ]]; then
    printf '∎'%.0s {2..$SHLVL}
  fi
}
PROMPT='%(#.%{$fg_bold[yellow]%}.%{$fg_bold[white]%})$(prompt_zsh_level)%(#.∷.→)%{$reset_color%} '
RPROMPT='%{$fg_bold[green]%}%c%{$fg_bold[white]%}:%{$fg_bold[blue]%}%m %{$fg_bold[red]%}$(vcprompt)%{$reset_color%}'

# Override prompt for Beamer or Emacs
if [ "$ITERM_PROFILE" = 'Beamer' ]; then
  PROMPT='➔ '
elif [ -n "$EMACS" ] ; then
  PROMPT='$ '
fi

### Options from PeepCode ##################################
setopt CORRECT
setopt CORRECTALL

setopt HIST_IGNORE_DUPS     # ignore duplication command history list
setopt SHARE_HISTORY        # share command history data
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY # write history only when closing
setopt EXTENDED_HISTORY # add more info

setopt NOCLOBBER

autoload url-quote-magic
zle -N self-insert url-quote-magic

HISTFILE=~/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

REPORTTIME=10 # Show elapsed time if command took more than X seconds
LISTMAX=0 # ask to complete if top of list would scroll off screen

# Make CTRL-W delete after other chars, not just spaces
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}

bindkey -e

autoload -U edit-command-line
zle -N edit-command-line
bindkey '\ee' edit-command-line

bindkey '\eq' push-line-or-edit
