#!/bin/zsh

### Options ################################################
# I got this stuff from random browsing through man zshoptions

setopt AUTO_CD       # '$ foo' means '$ cd foo' if 'foo' is not a command
setopt AUTO_PUSHD    # 'cd' is now cooler

### Prompt #################################################
autoload -U colors
colors
setopt prompt_subst
setopt transient_rprompt
PROMPT='%{$fg_bold[white]%}→%{$reset_color%} '
RPROMPT='%{$fg_bold[green]%}%c%{$fg_bold[white]%}:%{$fg_bold[blue]%}%m %{$fg_bold[red]%}$(vcprompt)%{$reset_color%}'

### Options from PeepCode ##################################
setopt CORRECT
setopt CORRECTALL

setopt HIST_IGNORE_DUPS     # ignore duplication command history list
setopt SHARE_HISTORY        # share command history data
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY # write history only when closing
setopt EXTENDED_HISTORY # add more info

autoload url-quote-magic
zle -N self-insert url-quote-magic

HISTFILE=~/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

REPORTTIME=10 # Show elapsed time if command took more than X seconds
LISTMAX=0 # ask to complete if top of list would scroll off screen

# Load completions for Ruby, Git, etc.
autoload compinit
compinit

# Make CTRL-W delete after other chars, not just spaces
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}

bindkey -e

autoload -U edit-command-line
zle -N edit-command-line
bindkey '\ee' edit-command-line

bindkey '\eq' push-line-or-edit
