#!/bin/zsh
#
autoload -U colors
colors

setopt AUTO_CD              # 'foo' instead of 'cd foo'
setopt AUTO_PUSHD           # cd pushes on dir stack
setopt CDABLE_VARS          # 'cd foo` instead of 'cd ~foo` when $foo is a dir

setopt PROMPT_SUBST         # allow expansion and substitution in prompt
setopt TRANSIENT_RPROMPT    # removes rprompt litter

setopt HIST_IGNORE_DUPS     # ignore duplication command history list
setopt SHARE_HISTORY        # share history across all sessions
setopt HIST_IGNORE_SPACE    # don't push commands starting with space in history
setopt APPEND_HISTORY       # append to history instead of overriding it
setopt EXTENDED_HISTORY     # add more info

setopt BRACECCL             # expand {a-z123} to a … z 1 2 3
setopt NOCLOBBER            # don't allow redirection to clobber files

setopt CORRECT              # simulate Clippy

HISTFILE=~/.zsh_history     # where to keep zsh history
SAVEHIST=30000              # history max
HISTSIZE=30000

REPORTTIME=10               # show elapsed time if command took more than X seconds
LISTMAX=0                   # ask to complete if top of list would scroll off screen
DIRSTACKSIZE=10             # limit dir stack size

# Make CTRL-W delete after other chars, not just spaces
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}

. ~/.zsh/prompt

# Disable ctrl-s and ctrl-q
# stty -ixon -ixoff

# Don't exit on C-d outside tmux
[[ -z "$TMUX" ]] && setopt IGNORE_EOF

# Do not allow duplicates in tables
typeset -U path

# Keybindings

bindkey -e

autoload -U url-quote-magic
autoload -U edit-command-line

function tmux-page-up() { [[ -n $TMUX ]] && tmux copy-mode -u }

zle -N edit-command-line
zle -N self-insert url-quote-magic
zle -N tmux-page-up

bindkey '\ee' edit-command-line
bindkey '\eq' push-line-or-edit
bindkey '\e[5~' tmux-page-up

which bat > /dev/null && export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PAGER="less"
