#!/usr/bin/env zsh

source setup/shared

determine-os-and-distro

# XDG
mkdir -p ~/.config/

# Bash
establish-link bash ~/.bash clobberable
establish-link bash_profile ~/.bash_profile clobberable

# Mutt
establish-link mutt ~/.mutt

# Scripts
establish-link scripts ~/.scripts

# Vim
establish-link vim ~/.vim
establish-link gvimrc ~/.gvimrc
establish-link vimrc ~/.vimrc

# ZSH
establish-link zsh ~/.zsh
establish-link zprofile ~/.zprofile
establish-link zshenv ~/.zshenv
establish-link zshrc ~/.zshrc

# Git
establish-link gitconfig ~/.gitconfig

# Ruby
establish-link gemrc ~/.gemrc
establish-link pryrc ~/.pryrc

# Tmux
establish-link tmux.conf ~/.tmux.conf

establish-link nvim    ~/.config/nvim
establish-link kitty   ~/.config/kitty
establish-link wezterm ~/.config/wezterm

establish-link config/ranger ~/.config/ranger

establish-link bin ~/.bin

mkdir -p ~/.vim-backup
mkdir -p ~/.vim-undo

if [[ -z $WITHOUT_PACKS ]]; then
  mkdir -p ~/.config/cheat/
  cat <<END > ~/.config/cheat/conf.yml
  ---
  editor: vim
  colorize: true
  style: monokai
  formatter: terminal16m
  pager: less -FRXS

  cheatpaths:
    - name: personal
      path: $HOME/code/personal/dotfiles/knowledge/cheat/
      tags: [ personal ]
      readonly: false
END

  if [[ $DOTFILES_OS == 'mac' ]]; then
    establish-pack mac_setup
  fi

  establish-pack pyenv
  establish-pack homebrew
  establish-pack tools
  establish-pack plenv
  establish-pack pyenv
  establish-pack rbenv
  establish-pack rustup
  establish-pack neovim
  establish-pack volta
  establish-pack ranger
  establish-pack perl-support
fi

