#!/bin/bash
alias reload_aliases="source ~/.bash/aliases"
alias aliases="vim ~/.bash/aliases && reload_aliases"
alias localrc="vim ~/.localrc && source ~/.localrc"

alias o="open ."

alias r="rake"
alias rg="rails generate"
alias rt="RAILS_ENV=test rake"
alias rtsr="RAILS_ENV=test rake solr:stop solr:reset solr:start"
alias rdsr="RAILS_ENV=development rake solr:stop solr:reset solr:start"
alias rdm="rake db:migrate"
alias rdmr="rake db:migrate:redo"
alias rdtp="rake db:test:prepare"
alias rrs="rake spec"
alias rc="rake cucumber"

alias rmig="rails generate migration"

alias g="git"
alias grm="git rebase origin/master"
alias grim="git rebase -i origin/master"
alias gs="git stash"
alias gsa="git stash apply"
alias gsc="git stash clear"
alias gsp="git stash pop"
alias grc="git rebase --continue"
alias gca="git commit --amend"
alias gr10="git rebase -i HEAD~10"

alias sr="script/runner"
alias sg="script/generate"
alias sdb="script/dbconsole"
alias sc="script/console"
alias ss="script/server"

alias t="tmux"
alias ta="tmux attach"

alias m="mate"
alias be="bundle exec"
alias vii="mvim --remote-silent"
alias gemopen="BUNDLER_EDITOR=mate bundle open"
