#!/bin/bash
alias reload_aliases="source ~/.bash/aliases"
alias aliases="vim ~/.bash/aliases && reload_aliases"
alias localrc="vim ~/.localrc && source ~/.localrc"

alias o="open ."

alias r="bundle exec rake"
alias rg="rails generate"
alias rt="RAILS_ENV=test r"
alias rdm="r db:migrate"
alias rdmr="r db:migrate:redo"
alias rdtp="r db:test:prepare"
alias rrs="r spec"
alias rc="r cucumber"

alias rmig="rails generate migration"

alias g="git"
alias gg="git status"
alias grm="git rebase origin/master"
alias grim="git rebase -i origin/master"
alias gs="git stash"
alias gsa="git stash apply"
alias gsc="git stash clear"
alias gsp="git stash pop"
alias grc="git rebase --continue"
alias gca="git commit --amend"
alias gr10="git rebase -i HEAD~10"

alias t="tmux"
alias ta="tmux attach"

alias m="mate"
alias be="bundle exec"
alias vii="mvim --remote-silent"
alias gemopen="BUNDLER_EDITOR=mate bundle open"

alias ree="RUBY_HEAP_MIN_SLOTS=1000000 RUBY_HEAP_SLOTS_INCREMENT=1000000 RUBY_HEAP_SLOTS_GROWTH_FACTOR=1 RUBY_GC_MALLOC_LIMIT=1000000000 RUBY_HEAP_FREE_MIN=500000"

alias spj="ree bundle exec xvfb-run specjour --rsync-port=8991"
alias spjs="ree bundle exec xvfb-run specjour spec --rsync-port=8991"
