#!/bin/bash
alias reload_aliases="source ~/.bash/aliases"
alias aliases="vim ~/.bash/aliases && reload_aliases"
alias localrc="vim ~/.localrc && source ~/.localrc"

alias tmux="tmux -2"

alias rake="noglob rake"
alias rdm="bundle exec rake db:migrate"
alias rdtp="bundle exec rake db:test:prepare"
alias rdmr="bundle exec rake db:migrate:reset"
alias rrs="bundle exec rake spec"
alias rc="bundle exec rake cucumber"

alias rg="rails generate"
alias rmig="rails generate migration"

alias g="git"
alias gp="git push"
alias gg="git status"
alias grm="git rebase origin/master"
alias grim="git rebase -i origin/master"
alias gs="git stash"
alias gsa="git stash apply"
alias gsc="git stash clear"
alias gsp="git stash pop"
alias grc="git rebase --continue"
alias gca="git commit --amend"
alias gr10="git rebase -i HEAD~10"
alias gdc="echo \"You mean 'gds', right?\""
alias gds="git diff --cached"
alias gri='git rebase -i $(git rev-list --all --merges | head -1)'

alias t="tmux"
alias ta="tmux-attach-current"
alias tat="tmux attach"

alias m="make"
alias be="bundle exec"
alias vii="mvim --remote-silent"
alias gemopen="bundle open"

alias ree="RUBY_HEAP_MIN_SLOTS=1000000 RUBY_HEAP_SLOTS_INCREMENT=1000000 RUBY_HEAP_SLOTS_GROWTH_FACTOR=1 RUBY_GC_MALLOC_LIMIT=1000000000 RUBY_HEAP_FREE_MIN=500000"

alias spj="ree bundle exec xvfb-run specjour --rsync-port=8991"
alias spjs="ree bundle exec xvfb-run specjour spec --rsync-port=8991"
alias spjf="ree bundle exec xvfb-run specjour features --rsync-port=8991"
alias spp="bundle exec specjour prepare --rsync-port=8991"

alias clj="rlwrap --quote-characters=\"'\" --command clojure clj"

if [[ -n $ZSH_NAME ]]; then
    alias -g RERR="2>&1"
fi
