#!/usr/bin/env zsh

if which rbenv > /dev/null; then
  export RBENV_SHELL=zsh

  rbenv() {
    local command
    command="${1:-}"

    if [ "$#" -gt 0 ]; then
      shift
    fi

    case "$command" in
    rehash|shell)
      eval "$(rbenv "sh-$command" "$@")";;
    *)
      command rbenv "$command" "$@";;
    esac
  }
fi

