#!/usr/bin/env zsh

function() {
    if [[ -z ${path[(r)$1]} ]]; then
        print "Load"
        path=($1 $path)
    else
        print "Don't"
    fi
} ~/.rbenv/bin

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
