#!/usr/bin/env zsh

if which pyenv > /dev/null; then
  export PYENV_SHELL=zsh

  pyenv() {
    local command
    command="${1:-}"

    if [ "$#" -gt 0 ]; then
      shift
    fi

    case "$command" in
    rehash|shell)
      eval "$(pyenv "sh-$command" "$@")";;
    *)
      command pyenv "$command" "$@";;
    esac
  }
fi
