#!/usr/bin/env zsh

if which nvim > /dev/null; then
  DOTFILES_VIM=${DOTFILES_VIM:-nvim}
fi

if [[ -n $DOTFILES_WSL ]] && which neovide.exe > /dev/null; then
  neovide() {
    (neovide.exe --nofork --wsl $* 2>&1 > /dev/null &)
  }

  DOTFILES_VIG=neovide
elif which neovide > /dev/null; then
  export NEOVIDE_MULTIGRID=true
  export NEOVIDE_FRAME=buttonless
  export NEOVIDE_TITLE_HIDDEN=true
  export NEOVIDE_FORK=true
  DOTFILES_VIG=${DOTFILES_VIG:-neovide}
elif which nvim-qt > /dev/null; then
  nvim-qt() {
    (NVIM_QT=1 command nvim-qt $* > /dev/null 2>&1 &)
  }
  DOTFILES_VIG=${DOTFILES_VIG:-nvim-qt}
fi

DOTFILES_VIM=${DOTFILES_VIM:-vim}

case $DOTFILES_OS in
  (linux)
    DOTFILES_VIG=${DOTFILES_VIG:-command gvim}
    ;;
  (mac)
    DOTFILES_VIG=${DOTFILES_VIG:-command mvim}
    ;;
  (*)
    DOTFILES_VIG=${DOTFILES_VIG:-command gvim}
    ;;
esac

alias vim=$DOTFILES_VIM
alias vig=$DOTFILES_VIG

export EDITOR=$DOTFILES_VIM
export VISUAL=$DOTFILES_VIM
export GIT_EDITOR=$DOTFILES_VIM
